const BRITTLE = Symbol.for('__brittle__')
const { kMain } = require('./lib/symbols')
if (!global[BRITTLE]) global[BRITTLE] = require('./brittle.js')
module.exports = global[BRITTLE]
module.exports.skip = global[BRITTLE].skip
module.exports.solo = global[BRITTLE].solo
module.exports.todo = global[BRITTLE].todo
module.exports.configure = global[BRITTLE].configure
module.exports.test = module.exports
module.exports[kMain] = global[BRITTLE][kMain]