#!/usr/bin/env node
const process = require('process')
const path = require('path')
const fs = require('fs')
const { command, arg, flag, bail, rest } = require('paparam')
const glob = require('./lib/glob')

const args = (process.env.BRITTLE || '').split(/\s|,/g).map(s => s.trim()).filter(s => s).concat(process.argv.slice(2))

const cmd = command('brittle-make-test',
  arg('<outfile>', 'Generates an out file that contains all target tests'),
  flag('--solo, -s', 'Engage solo mode'),
  flag('--bail, -b', 'Bail out on first assert failure'),
  flag('--unstealth, -u', 'Print out assertions even if stealth is used'),
  flag('--timeout, -t <timeout>', 'Set the test timeout in milliseconds (default: 30000)'),
  rest('<files>'),
  bail((bail) => {
    console.log(bail.reason)
    console.log(bail.command.usage())
    process.exit(1)
  })
).parse(args)
if (cmd === null) process.exit(0)
if (cmd.flags.runner === true) {
  console.error('--runner must be a path to the generated test runner')
  process.exit(2)
}

const files = glob(cmd.rest)
runner(cmd.args.outfile, files, cmd.flags)

function runner (file, files, { bail, solo, unstealth, timeout }) {
  console.log('file', file)
  const out = path.resolve(file)
  const dir = path.dirname(out)

  let s = ''

  s += 'runTests()\n\nasync function runTests () {\n  const test = (await import(\'brittle\')).default\n\n'

  if (bail || solo || unstealth || timeout) {
    s += `  test.configure({ bail: ${!!bail}, solo: ${!!solo}, unstealth: ${!!unstealth}, timeout: ${timeout} })\n`
  }

  s += '  test.pause()\n\n'

  for (const f of files) {
    const t = path.resolve(f)
    if (t === out) continue

    let r = path.relative(dir, t).replace(/\\/g, '/')
    if (r[0] !== '.') r = './' + r
    s += '  await import(\'' + r + '\')\n'
  }

  s = s.trimRight()

  s += '\n\n  test.resume()\n}\n'
  s = '// This runner is auto-generated by Brittle\n\n' + s

  try {
    fs.mkdirSync(dir)
  } catch {}

  fs.writeFileSync(out, s)
}
