name: Test with Bare

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x64

          - os: macos-latest
            platform: darwin
            arch: x64

          - os: windows-latest
            platform: win32
            arch: x64

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.platform }}-${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Setup bare
        run: npm i -g bare-runtime

      - name: Install dependencies
        run: npm i

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test:bare
